CREATE TABLE IF NOT EXISTS outline(
  outlineID INT UNSIGNED NOT NULL AUTO_INCREMENT,  
  plot VARCHAR(5000) NOT NULL,
  comments VARCHAR(2500) NOT NULL,
  PRIMARY KEY (outlineID)
) ENGINE=INNODB CHARACTER SET utf8mb4;